[dev]
  publish = "./site/"

[build]
  functions = "./site"

[[redirects]]
  from = "/sample/*"
  to = "https://bullish-sample.s3-us-west-2.amazonaws.com/index.html"
  status = 200

[[redirects]]
  from = "/archive/"
  to = "https://bullish-archive.s3-us-west-2.amazonaws.com/index.html"
  status = 200

[[redirects]]
  from = "/archive/*"
  to = "https://bullish-archive.s3-us-west-2.amazonaws.com/:splat"
  status = 200
